version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: lms_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z

  server:
    build: ./server
    container_name: lms_server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL=postgresql://admin:password123@db:5432/lms_database?schema=public
    depends_on:
      - db
    # Lệnh này đảm bảo Prisma gen type và chạy deploy migrations trước khi chạy server
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node server.js"
volumes:
  pgdata:
