FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
COPY prisma.config.mjs ./

RUN npm install

COPY . .

# Generate Prisma client using the defined schema
RUN npx prisma generate

EXPOSE 5000

CMD ["node", "server.js"]
